# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, res
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 619)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1100, 619))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 550, 619))
        self.label.setStyleSheet("border-image: url(:/images/4.jpg);\n"
"")
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(550, 0, 550, 619))
        self.widget_2.setStyleSheet("background-color:rgb(3, 22, 19);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.usernameCred = QtWidgets.QLineEdit(self.widget_2)
        self.usernameCred.setGeometry(QtCore.QRect(137, 350, 275, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.usernameCred.setFont(font)
        self.usernameCred.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.usernameCred.setStyleSheet("background-color:rgba(208, 253, 246, 0.94);\n"
"color:rgb(3, 22, 19);\n"
"border-radius: 4px;\n"
"padding-left: 10px;\n"
"padding-bottom: 3px;\n"
"")
        self.usernameCred.setText("")
        self.usernameCred.setObjectName("usernameCred")
        self.passwordCred = QtWidgets.QLineEdit(self.widget_2)
        self.passwordCred.setGeometry(QtCore.QRect(137, 400, 275, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.passwordCred.setFont(font)
        self.passwordCred.setStyleSheet("background-color:rgba(208, 253, 246, 0.94);\n"
"color:rgb(3, 22, 19);\n"
"border-radius: 4px;\n"
"padding-left: 10px;\n"
"padding-bottom: 3px;\n"
"")
        self.passwordCred.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordCred.setText("")
        self.passwordCred.setFrame(True)
        self.passwordCred.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordCred.setObjectName("passwordCred")
        self.loginButton = QtWidgets.QPushButton(self.widget_2)
        self.loginButton.setGeometry(QtCore.QRect(137, 450, 275, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton#loginButton{\n"
"background-color:rgb(119, 205, 249);\n"
"color:rgb(3, 22, 19);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#loginButton:pressed{\n"
"background-color:rgb(208, 253, 246);\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(180, 50, 70, 80))
        self.label_2.setStyleSheet("border-image: url(:/symbols/shovelandpickaxesymbol.png);\n"
"background-color: rgb(18, 36, 33);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(270, 50, 70, 70))
        self.label_3.setStyleSheet("border-image: url(:/symbols/wizardhatsymbol.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(100, 170, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(45)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(200, 260, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(30, 520, 491, 31))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_6.setObjectName("label_6")
        self.toRegisterPageButton = QtWidgets.QPushButton(self.widget_2)
        self.toRegisterPageButton.setGeometry(QtCore.QRect(232, 560, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.toRegisterPageButton.setFont(font)
        self.toRegisterPageButton.setStyleSheet("QPushButton#toRegisterPageButton{\n"
"background-color:rgb(119, 205, 249);\n"
"color:rgb(3, 22, 19);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#toRegisterPageButton:pressed{\n"
"background-color:rgb(208, 253, 246);\n"
"}")
        self.toRegisterPageButton.setObjectName("toRegisterPageButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.usernameCred.setPlaceholderText(_translate("Form", "Enter Username Here"))
        self.passwordCred.setPlaceholderText(_translate("Form", "Enter Password Here"))
        self.loginButton.setText(_translate("Form", "L o g i n "))
        self.label_4.setText(_translate("Form", "Trail Wizards"))
        self.label_5.setText(_translate("Form", "Dig. Build. Shred."))
        self.label_6.setText(_translate("Form", "PSST! Hey you! Yeah you. First time here? No worries! Register here now and become a Trail Wizard!"))
        self.toRegisterPageButton.setText(_translate("Form", "Register"))
import res_rc
import symbolres_rc
