# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 619)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1100, 619))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 550, 619))
        self.label.setStyleSheet("border-image: url(:/images/4.jpg);\n"
"")
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(550, 0, 550, 619))
        self.widget_2.setStyleSheet("background-color: rgb(18, 36, 33);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(137, 320, 275, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setStyleSheet("background-color:rgba(208, 253, 246, 0.94);\n"
"color:rgb(3, 22, 19);\n"
"border-radius: 4px;\n"
"padding-left: 10px;\n"
"padding-bottom: 3px;\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(137, 370, 275, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(208, 253, 246, 0.94);\n"
"color:rgb(3, 22, 19);\n"
"border-radius: 4px;\n"
"padding-left: 10px;\n"
"padding-bottom: 3px;\n"
"")
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.registerButton = QtWidgets.QPushButton(self.widget_2)
        self.registerButton.setGeometry(QtCore.QRect(137, 490, 275, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("QPushButton#registerButton{\n"
"background-color:rgb(119, 205, 249);\n"
"color:rgb(3, 22, 19);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#registerButton:pressed{\n"
"background-color:rgb(208, 253, 246);\n"
"}")
        self.registerButton.setObjectName("registerButton")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 70, 70))
        self.label_3.setStyleSheet("border-image: url(:/images/wizardhatsymbol.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(100, 90, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(45)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(80, 530, 381, 31))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_6.setObjectName("label_6")
        self.toRegisterPageButton = QtWidgets.QPushButton(self.widget_2)
        self.toRegisterPageButton.setGeometry(QtCore.QRect(232, 570, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.toRegisterPageButton.setFont(font)
        self.toRegisterPageButton.setStyleSheet("QPushButton#toRegisterPageButton{\n"
"background-color:rgb(119, 205, 249);\n"
"color:rgb(3, 22, 19);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#toRegisterPageButton:pressed{\n"
"background-color:rgb(208, 253, 246);\n"
"}")
        self.toRegisterPageButton.setObjectName("toRegisterPageButton")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(180, 10, 70, 80))
        self.label_2.setStyleSheet("border-image: url(:/images/shovelandpickaxesymbol.png);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(137, 220, 275, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_3.setStyleSheet("background-color:rgba(208, 253, 246, 0.94);\n"
"color:rgb(3, 22, 19);\n"
"border-radius: 4px;\n"
"padding-left: 10px;\n"
"padding-bottom: 3px;\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(190, 150, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(137, 270, 275, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_4.setStyleSheet("background-color:rgba(208, 253, 246, 0.94);\n"
"color:rgb(3, 22, 19);\n"
"border-radius: 4px;\n"
"padding-left: 10px;\n"
"padding-bottom: 3px;\n"
"")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(130, 410, 301, 21))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(150, 430, 291, 16))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.generatePasswordButton = QtWidgets.QPushButton(self.widget_2)
        self.generatePasswordButton.setGeometry(QtCore.QRect(210, 450, 125, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.generatePasswordButton.setFont(font)
        self.generatePasswordButton.setStyleSheet("QPushButton#generatePasswordButton{\n"
"background-color:rgb(8, 188, 160);\n"
"color:rgb(3, 22, 19);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#generatePasswordButton:pressed{\n"
"background-color:rgb(208, 253, 246);\n"
"}")
        self.generatePasswordButton.setObjectName("generatePasswordButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter Username Here"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Enter Password Here"))
        self.registerButton.setText(_translate("Form", "R e g i s t e r"))
        self.label_4.setText(_translate("Form", "Trail Wizards"))
        self.label_5.setText(_translate("Form", "Welcome! Fill out the form below and click the register button to join Trail Wizards!"))
        self.label_6.setText(_translate("Form", "Are you already a Trail Wizard? Click the button below to go to the Login page."))
        self.toRegisterPageButton.setText(_translate("Form", "Login"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Enter your full name"))
        self.label_7.setText(_translate("Form", "Dig. Build. Shred."))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Enter your Email"))
        self.label_8.setText(_translate("Form", "Can\'t think of a good password? Try our Password Generator!"))
        self.label_9.setText(_translate("Form", "Generate a Secure Password at the Click of a Button!"))
        self.generatePasswordButton.setText(_translate("Form", "Generate Password"))
import imageandsymbolres_rc
